export const data = [
  {
    key: 1,
    name: "Ajanlekoko Zaynab",
    age: "18",
    level: "200l",
    height: "1.5 Meters",
    hobbies: "Jumping, Basketball, Running, Boxing, Baking",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
  {
    key: 2,
    name: "Ajanlekoko Hairat",
    age: "19",
    level: "300l",
    height: "1.8 Meters",
    hobbies: "Jumping, Basketball, Running, Boxing, Baking",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
  {
    key: 3,
    name: "Ayanwumi Abdulroheem",
    age: "21",
    level: "400l",
    height: "2.4 Meters",
    hobbies: "Jumping, Basketball, Running, Boxing, Baking",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
  {
    key: 4,
    name: "Hannat Salawu",
    age: "18",
    level: "200l",
    height: "1.5 Meters",
    hobbies: "Jumping, Basketball, She cant run, Boxing, Eeke-Eebu",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
  {
    key: 5,
    name: "Ajanlekoko Zaynab",
    age: "18",
    level: "200l",
    height: "1.5 Meters",
    hobbies: "Jumping, Basketball, Running, Boxing, Baking",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
  {
    key: 6,
    name: "Ajanlekoko Zaynab",
    age: "18",
    level: "200l",
    height: "1.5 Meters",
    hobbies: "Jumping, Basketball, Running, Boxing, Baking",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
  {
    key: 7,
    name: "Ajanlekoko Zaynab",
    age: "18",
    level: "200l",
    height: "1.5 Meters",
    hobbies: "Jumping, Basketball, Running, Boxing, Baking",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
  {
    key: 8,
    name: "Ajanlekoko Zaynab",
    age: "18",
    level: "200l",
    height: "1.5 Meters",
    hobbies: "Jumping, Basketball, Running, Boxing, Baking",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
  {
    key: 9,
    name: "Ajanlekoko Zaynab",
    age: "18",
    level: "200l",
    height: "1.5 Meters",
    hobbies: "Jumping, Basketball, Running, Boxing, Baking",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
  {
    key: 10,
    name: "Ajanlekoko Zaynab",
    age: "18",
    level: "200l",
    height: "1.5 Meters",
    hobbies: "Jumping, Basketball, Running, Boxing, Baking",
    department: "Food Technology",
    title: "I really love the coding school",
    review:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda sed esse ea enim architecto voluptatibus at libero, dolorum iure facilis",
  },
];
